let cadenax = 'Hola Mundo';
console.log(typeof cadenax);
document.write(cadenax, " y su typeof es " + typeof cadenax  +  "<br/>" +  "y su longitud es " + cadenax.length + "<br/><br/>");
console.log(cadenax.length);
document.write("Los strings son inmutables, no pueden ser modificados una vez creados" + "<br/>");
document.write("Los strings tienen un indice que empieza en 0 como la cadenax de Hola mundo" + "<br/>");
document.write("donde la H es el indice 0 = "+ cadenax[0] + " y el indice 3 es la a = "+ cadenax[3] + "<br/>");
cadenax[4] = "--";
document.write("No puedo hacer esto cadenax[3] = 'b' porque es inmutable" + "<br/>" + "me trae el mismo mensaje que escribi al principio "+ cadenax+ "<br/>");
document.write("si escribo cadenax[20] me trae undefined porque no existe el indice 20 = " + cadenax[20] + "<br/>");
document.write("Si quiero consultar la ultima cadenax es el largo de la cadenax - 1 = " + cadenax[cadenax.length - 1] + "<br/>");
document.write("o tambien la cadenax - 1 o -2 etc = " + cadenax[cadenax.length - 2] + "<br/>");
document.write("<br/><br/>");